### ISSUE TITLE
[BUG] Can't Install "App Not Available: This app is currently not available in your country or region."

### ISSUE THREAD

**Issue by ChristopherA** [yuanzhoucq/Tab-Space#106]
**Describe the bug**

Can't install Tab Space.

**To Reproduce**
I have tried to install Tab Space in the US Mac App Store using both `https://apps.apple.com/app/tab-space/id1473726602?mt=12` and `mas install 1473726602`.

When I go to that URL, I get "App Not Available: This app is currently not available in your country or region." I am in the US region.

**Expected behavior**

Install app.

**Desktop (please complete the following information):**
 - OS: 15.1 Beta (24B5070a)

**Additional context**

**Comment by ChristopherA** [comment]
I just tried searching for "Tab Space" in the US Mac App Store, and I get "No Mac App results found."

**Comment by yuanzhoucq** [comment]
Apple has restored Tab Space to the App Store.
