### ISSUE TITLE
Bug Report - Tabs not saved when exiting Safari too quickly

### ISSUE THREAD

**Issue by 1kc** [yuanzhoucq/Tab-Space#14]
当保存标签页后立即退出Safari，已关闭的标签页不会保存。

Steps to reproduce:
1. Open tabs
2. Click Save & Close tabs
3. Quit safari/ CMD + Q
4. Reopen Safari
5. Open Tab Space
6. Tabs from previous session are not there

**Comment by yuanzhoucq** [comment]
Hi，感谢提交 Bug，这个问题其实我知道，主要问题在于使用的苹果存储机制只会写入内存，而内存到硬盘的写入由系统自行决定，以至于太快关闭时还没有写入。

目前我正在迁移 Tab Space 的内部存储方式，完成迁移后会着手解决这个问题！

**Comment by 1kc** [comment]
OK 谢谢。一般非常好用！👏👏

**Comment by yuanzhoucq** [comment]
从 3.5 版本采用了新的存储方式后测试已经无此问题~
