### ISSUE TITLE
Dropped compatibility with 10.14 Mojave?

### ISSUE THREAD

**Issue by gingerbeardman** [yuanzhoucq/Tab-Space#16]
I see latest update says this now needs 10.15 Catalina?

![Screen shot 2020-05-01 at 09 36 08](https://user-images.githubusercontent.com/49612/80793511-3987b280-8b8f-11ea-93d6-eb2a08a210eb.png)

I'm still on 10.14 Mojave, so I'm interested in whether you can lower the minimum criteria? Otherwise, why does this now need 10.15?

Thanks

**Comment by yuanzhoucq** [comment]
It was a hard decision. 

I am working for the automatic saving feature, which would generate many sessions in the background. So I now onboard Core Data as the database. And from macOS 10.15 it has the out-of-box iCloudKit support. 

Besides, I am writing a native management interface as well using SwiftUI. Thus, sooner or later macOS would be a must for this project : )

**Comment by gingerbeardman** [comment]
Deeply disappointing. 

Interestingly, you make no mention of consideration for your users in this decision.

What version of macOS do your users use in your iTunes/App Store Analytics?

**Comment by yuanzhoucq** [comment]
About 80% of Tab Space users are on macOS 10.15.

But why you would think I did not consider my users? 😂 Current users won't lose anything if they do not upgrade. They can keep using all the existing functions forever. 

The only purpose of making this SDK upgrading is to develop some exciting new features.

**Comment by yuanzhoucq** [comment]
> I'm still on 10.14 Mojave, so I'm interested in whether you can lower the minimum criteria? Otherwise, why does this now need 10.15?

More specific, it is [NSPersistentCloudKitContainer](https://developer.apple.com/documentation/coredata/nspersistentcloudkitcontainer) which depends on macOS 10.15 now. I am sorry I didn't find a simple way to work around this.

**Comment by gingerbeardman** [comment]
Thanks for the stats!

I'll remain on the older version whilst I look for an alternative.

Best of luck with the app in future.

**Comment by yuanzhoucq** [comment]
> Thanks for the stats!
> 
> You did not mention users in your decision to move to 10.15, which is why I assumed you did not consider them primarily.
> 
> I'll remain on the older version whilst I get all my tabs out back into being managed by Safari itself.
> 
> Best of luck with the app in the future.

After doing some research, I found it possible to bring back the compatibility with 10.14 or even 10.13. I will try to implement this idea in next version : )

**Comment by gingerbeardman** [comment]
Thank you. It's very much appreciated.

**Comment by gingerbeardman** [comment]
Thanks for re-adding support for 10.14 and 10.13!

I got the update this week.
