### ISSUE TITLE
Feature Request--remove repeated item

### ISSUE THREAD

**Issue by Raphael-Hao** [yuanzhoucq/Tab-Space#17]
建议加入去重

**Comment by yuanzhoucq** [comment]
具体是指保存标签页时不保存重复页面吗？

**Comment by Raphael-Hao** [comment]
嗯，对，现在有这个功能吗？

**Comment by yuanzhoucq** [comment]
最新的 3.6 版本已经有这个功能啦~

**Comment by Raphael-Hao** [comment]
<img width="585" alt="image" src="https://user-images.githubusercontent.com/19326656/81309175-37ed4b80-90b5-11ea-83ce-1fb053f254c1.png">
是有什么需要设置的吗，因为我看我现在是不行的

**Comment by yuanzhoucq** [comment]
哦哦，沟通理解错误，我是指在同一组 session 保存的时候会自动去重，但是不同 session 之间目前是没有检测的。

**Comment by Raphael-Hao** [comment]
感觉很多时候把session内的tab打开以后，在再次关闭的时候可能有新增的了，这个时候如果有去重还是很有用的感觉

**Comment by yuanzhoucq** [comment]
好的，感谢建议，我会考虑后续添加这个功能 😄

**Comment by yuanzhoucq** [comment]
已在 3.6.3 版本中添加
