### ISSUE TITLE
Feature Request--Hotkey management

### ISSUE THREAD

**Issue by jayden-liu** [yuanzhoucq/Tab-Space#19]
可以禁用指定快捷键或是支持快捷键键位修改吗？因为可能存在某些快捷键用不到或是快捷键冲突的情况。

**Comment by yuanzhoucq** [comment]
目前还不可以，只能禁用全部或打开全部。
目前的快捷键是基于 js 的，在浏览器中存在特殊页面不可用和冲突的问题，后续我考虑把这部分移到原生程序中去，然后就可以解决问题并实现你所提的要求：）

**Comment by yuanzhoucq** [comment]
如果在原生程序中监听全局快捷键的话，就需要后台一直驻留一个进程了。所以我考虑针对原本使用快捷键冲突的用户，增加使用 `Shift` 快捷键的选项，已经在 3.7.1 版本中添加，请问这样能否解决你那边的冲突问题呢？

**Comment by jayden-liu** [comment]
很完美地解决了我的问题，非常感谢
