### ISSUE TITLE
Enhancement--Add Italian language support

### ISSUE THREAD

**Issue by edoguido** [yuanzhoucq/Tab-Space#21]
Hi! Finally a good solution for tab management in Safari.
I've just translated the strings into Italian. 

Thanks for this good piece of software!
[tab_space-it.json.zip](https://github.com/yuanzhoucq/Tab-Space/files/4663224/tab_space-it.json.zip)

**Comment by yuanzhoucq** [comment]
Thanks! Italian translation has been added in version 3.7.
