### ISSUE TITLE
Feature Request: Keyboard Shortcut to 'Save Current Tab'

### ISSUE THREAD

**Issue by setu4993** [yuanzhoucq/Tab-Space#22]
Thank you for creating and maintaining this app.

It'd be great to have a keyboard shortcut that can 'Save Current Tab' without any clicks or interactions.

**Comment by yuanzhoucq** [comment]
Thanks for your suggestion! I will add this soon : )

**Comment by setu4993** [comment]
Thanks, Yuan :).

**Comment by yuanzhoucq** [comment]
Added in version 3.7.
