### ISSUE TITLE
Icon looks bad on non retina display

### ISSUE THREAD

**Issue by theseal** [yuanzhoucq/Tab-Space#28]
The icon looks bad on a non retina display:
![Screenshot 2020-06-16 at 21 18 49](https://user-images.githubusercontent.com/818851/84818761-4c5b2700-b017-11ea-9e59-d3d5f73755a7.png)

and

![Screenshot 2020-06-16 at 21 19 48](https://user-images.githubusercontent.com/818851/84818770-4feeae00-b017-11ea-9eb5-ea818f15c09a.png)

**Comment by yuanzhoucq** [comment]
That's awful 😱

I will solve it in later version 😅

**Comment by yuanzhoucq** [comment]
Fixed in version 3.8 : )
