### ISSUE TITLE
Lost all saved tabs after upgrading to safari 13

### ISSUE THREAD

**Issue by dawnmy** [yuanzhoucq/Tab-Space#3]
I lost all saved tabs after upgrading to safari 13, and now the tab space page is empty. Is there a way to restore all the tabs?

**Comment by yuanzhoucq** [comment]
I am very sorry that they cannot be restored. Something has changed in Safari 13, and I wrote a blog to explain it.
[Why I lost my tabs in Tab Space?](https://joyuer.cn/2019-09-25-why-i-lost-my-tabs/)
