### ISSUE TITLE
可否在 Tab 的右键菜单增加相关的功能

### ISSUE THREAD

**Issue by soffchen** [yuanzhoucq/Tab-Space#4]
像 Chrome 一样，右键点击当前 Tab 可以选择 Close Tabs to the Right (Tab Space 的 ^R) 这些功能，方便右手单手操作 :)

**Comment by yuanzhoucq** [comment]
@soffchen 非常愿意，但是苹果没有提供相关接口😂

**Comment by yuanzhoucq** [comment]
> 像 Chrome 一样，右键点击当前 Tab 可以选择 Close Tabs to the Right (Tab Space 的 ^R) 这些功能，方便右手单手操作 :)
