### ISSUE TITLE
Combine sessions and/or move tab between sessions

### ISSUE THREAD

**Issue by gingerbeardman** [yuanzhoucq/Tab-Space#5]
From Twitter: https://twitter.com/gingerbeardman/status/1190327127381557248

> @gingerbeardman:I'd like to be able to combine sessions and/or move tab between sessions. For example if I have two news sessions containing different sites I would like to drag and drop to combine them into one. Does this make sense?

> @yuanzhoucq: As a tab saver, no; as a bookmark manager, yes. I will consider this proposal but I can not ensure it. But thanks all the same for you suggestions! 😄😄

> @gingerbeardman: I can do it already using Safari bookmark manager. I just wanted to do it for sessions saved in Tab Space without having to open the sessions and work with Safari tabs and windows. It seems allowing arrangement between session in your web UI should be relatively easy? I can help.

**Comment by yuanzhoucq** [comment]
@gingerbeardman Hi Matt, I've added the drag and drop feature for Tab Space 3.1. Should be available very soon (after App Store CDN's processing). Thanks again for your suggestion!

**Comment by gingerbeardman** [comment]
Thank you!
